name: "Announce New Multi- Implementation"
description: Express interest in implementing a new multiformats implementation
title: "📚 [NEW PROJECT] - <title>"
labels: [
  "implementation"
]
body:
  - type: input
    id: name
    attributes:
      label: "Name"
      description: Name this multi-XX implementation in a word, if you can
      placeholder: (language)-Multi(project) is the default template
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: "Have read contributing"
      description: I have read the [contributing](./contributing.md) document
      options:
      - label: I read it!
    validations:
      required: true
  - type: textarea
    id: problem_statement
    attributes:
      label: "Description of problem solved"
      description: Please describe the problem solved by your implementation, what systems it will fit into, the form factor, etc
      placeholder: Feel free to provide links for context and use-case descriptions
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: "Have reviewed table"
      description: I have reviewed the [multiformats mega-table](https://github.com/multiformats/multicodec/blob/master/table.csv) to assess viable sub-namespace for a registry if applicable
      options:
      - label: I read it!
  - type: textarea
    id: solution_and_rationale
    attributes:
      label: "Proposed solution and rationale"
      description: Please describe at a high level if your implementation will cover all multiformats or just (a) specific registry/ies within in, and how it differs from existing implementations in the same language (if applicable). Note that testably implementing all "final" registrations of a given registry are required to be listed on that registry's specification as a conformant implementation.
      placeholder: Details welcome! 
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: "Want help"
      description: Check this box if you'd like potential helpers tagged into the thread for review.
      options:
      - label: Would collaborate!