blank_issues_enabled: true
contact_links:
  - name: Protocol Labs Vulnerability Disclosure Team
    url: mailto:security@ipfs.io
    about: Please do NOT open issues related to security of implementations or spec here without contacting the IPFS security team first.