name: "Register multi- Multi- Implementation"
description: Register a completec and conformant implementation of 2 or more multiformats
title: "📚 [NEW PROJECT] - <title>"
labels: [
  "implementation"
]
body:
  - type: input
    id: name
    attributes:
      label: "Name"
      description: Under what name can developers find this multi-XX implementation (say, as a library in package managers)
      placeholder: (language/framework)-Multi(projects) is the default template
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: "Have read contributing"
      description: I have read the [contributing](./contributing.md) document
      options:
      - label: I read it!
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: "Tests complete and passing"
      description: I have tested it against existing libraries using test cases in each multi repo
      options:
      - label: Tests pass!
    validations:
      required: true
  - type: textarea
    id: solution_and_rationale
    attributes:
      label: "Unique properties"
      description: Unique strengths, properties, or use-cases supported compared to other implementations.
      placeholder: Details welcome!   