name: "Translation Announcement"
description: Announcement of intent to translate
title: "📚 [TRANSLATION/LOCALIZATION] - <title>"
labels: [
  "community"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "Language or Localization offered"
      description: Please describe the language and/or alphabet/localization standard you would like to target for a translation and/or localization of this specification.
      placeholder: ISO codes always nice but not required!
    validations:
      required: true
  - type: checkbox
    id: want_help
    attributes:
      label: "Want help?"
      description: Check this box if you'd like potential helpers tagged into the thread for review.
      default: true
  - type: checkboxes
    attributes:
      label: "Want help"
      description: Check this box if you'd like potential helpers tagged into the thread for review.
    options:
      - label: Would collaborate!
      - default: true